name: Build and Release
on:
  release:
    types: [released]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: |
          npm run build
          cp package.json dist/package.json
          cp package-lock.json dist/package-lock.json

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.globalenergytransitions.org
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
